### ISSUE TITLE
CI/CD for Moderator FrontEnd

### ISSUE THREAD

**Issue by prakruti** [orcasound/aifororcas-livesystem#29]
Put in unit tests that will run for each PR.
Put in a build pipeline that will run for each PR.
Automated deployment of moderator portal after PR completes.

**Comment by rawlink** [comment]
PR is out and waiting for approval

**Comment by micowan** [comment]
Kenneth,

Sorry. Getting really randomized here. I approved the PR and merged it into main. Anything else I need to do to unblock this for you?


Michael Cowan | Senior Consultant

Microsoft Corporation

________________________________

**Comment by micowan** [comment]
Kenneth,

Two things:


  1.  Is the CI/CD pipeline for AI for Orcas still active? Just making sure before I post a change.
  2.  I need to upgrade the target framework (.NET Core 3.1 to .NET 6) for both deployed solutions. Is that something that is handled automatically or something someone would have to change the CI/CD pipeline for?


Michael Cowan | Senior Consultant

Microsoft Corporation

________________________________

**Comment by rawlink** [comment]
@micowan The pipeline should still be active. The .Net change will require an update to the pipeline.

``` yaml
env:
  DOTNET_VERSION: 3.1.x  # <--- This will need to be updated for both client and server pipelines.
  DOTNET_RUNTIME: win-x86
  WORKING_DIR: ModeratorFrontEnd/AIForOrcas/AIForOrcas.Server
  PUBLISH_DIR: output
  AZURE_APP_NAME: AIForOrcasDetections
```
